/*
	File Generated by NetTiers templates [www.nettiers.com]
	Generated on : July 10, 2013
	Important: Do not modify this file. Edit the file SqlMediaImageProvider.cs instead.
*/

#region using directives

using System;
using System.Data;
using System.Data.Common;
using System.Text;

using Microsoft.Practices.EnterpriseLibrary.Data;
using Microsoft.Practices.EnterpriseLibrary.Data.Sql;

using System.Collections;
using System.Collections.Specialized;

using System.Diagnostics;
using ShutterTale.Entities;
using ShutterTale.Data;
using ShutterTale.Data.Bases;

#endregion

namespace ShutterTale.Data.SqlClient
{
	///<summary>
	/// This class is the SqlClient Data Access Logic Component implementation for the <see cref="MediaImage"/> entity.
	///</summary>
	public abstract partial class SqlMediaImageProviderBase : MediaImageProviderBase
	{
		#region Declarations
		
		string _connectionString;
	    bool _useStoredProcedure;
	    string _providerInvariantName;
			
		#endregion "Declarations"
			
		#region Constructors
		
		/// <summary>
		/// Creates a new <see cref="SqlMediaImageProviderBase"/> instance.
		/// </summary>
		public SqlMediaImageProviderBase()
		{
		}
	
	/// <summary>
	/// Creates a new <see cref="SqlMediaImageProviderBase"/> instance.
	/// Uses connection string to connect to datasource.
	/// </summary>
	/// <param name="connectionString">The connection string to the database.</param>
	/// <param name="useStoredProcedure">A boolean value that indicates if we should use stored procedures or embedded queries.</param>
	/// <param name="providerInvariantName">Name of the invariant provider use by the DbProviderFactory.</param>
	public SqlMediaImageProviderBase(string connectionString, bool useStoredProcedure, string providerInvariantName)
	{
		this._connectionString = connectionString;
		this._useStoredProcedure = useStoredProcedure;
		this._providerInvariantName = providerInvariantName;
	}
		
	#endregion "Constructors"
	
		#region Public properties
	/// <summary>
    /// Gets or sets the connection string.
    /// </summary>
    /// <value>The connection string.</value>
    public string ConnectionString
	{
		get {return this._connectionString;}
		set {this._connectionString = value;}
	}
	
	/// <summary>
    /// Gets or sets a value indicating whether to use stored procedures.
    /// </summary>
    /// <value><c>true</c> if we choose to use use stored procedures; otherwise, <c>false</c>.</value>
	public bool UseStoredProcedure
	{
		get {return this._useStoredProcedure;}
		set {this._useStoredProcedure = value;}
	}
	
	/// <summary>
    /// Gets or sets the invariant provider name listed in the DbProviderFactories machine.config section.
    /// </summary>
    /// <value>The name of the provider invariant.</value>
    public string ProviderInvariantName
    {
        get { return this._providerInvariantName; }
        set { this._providerInvariantName = value; }
    }
	#endregion
	
		#region Get Many To Many Relationship Functions
		#endregion
	
		#region Delete Functions
		/// <summary>
		/// 	Deletes a row from the DataSource.
		/// </summary>
		/// <param name="_id">. Primary Key.</param>	
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <remarks>Deletes based on primary key(s).</remarks>
		/// <returns>Returns true if operation suceeded.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Delete(TransactionManager transactionManager, System.Guid _id)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.Media_Image_Delete", _useStoredProcedure);
			database.AddInParameter(commandWrapper, "@Id", DbType.Guid, _id);
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "Delete")); 

			int results = 0;
			
			if (transactionManager != null)
			{	
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
			
			//Stop Tracking Now that it has been updated and persisted.
			if (DataRepository.Provider.EnableEntityTracking)
			{
				string entityKey = EntityLocator.ConstructKeyFromPkItems(typeof(MediaImage)
					,_id);
                EntityManager.StopTracking(entityKey);
                
			}
			
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "Delete")); 

			commandWrapper = null;
			
			return Convert.ToBoolean(results);
		}//end Delete
		#endregion

		#region Find Functions

		#region Parsed Find Methods
		/// <summary>
		/// 	Returns rows meeting the whereClause condition from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <remarks>Operators must be capitalized (OR, AND).</remarks>
		/// <returns>Returns a typed collection of ShutterTale.Entities.MediaImage objects.</returns>
		public override TList<MediaImage> Find(TransactionManager transactionManager, string whereClause, int start, int pageLength, out int count)
		{
			count = -1;
			if (whereClause.IndexOf(";") > -1)
				return new TList<MediaImage>();
	
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.Media_Image_Find", _useStoredProcedure);

		bool searchUsingOR = false;
		if (whereClause.IndexOf(" OR ") > 0) // did they want to do "a=b OR c=d OR..."?
			searchUsingOR = true;
		
		database.AddInParameter(commandWrapper, "@SearchUsingOR", DbType.Boolean, searchUsingOR);
		
		database.AddInParameter(commandWrapper, "@Orientation", DbType.Byte, DBNull.Value);
		database.AddInParameter(commandWrapper, "@YcbCrPositioning", DbType.Byte, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ExposureTime", DbType.Double, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Fnumber", DbType.Double, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ExposureProgram", DbType.Byte, DBNull.Value);
		database.AddInParameter(commandWrapper, "@IsoSpeedRatings", DbType.Int16, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ShutterSpeedValue", DbType.Double, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ApertureValue", DbType.Double, DBNull.Value);
		database.AddInParameter(commandWrapper, "@MeteringMode", DbType.Byte, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Flash", DbType.Byte, DBNull.Value);
		database.AddInParameter(commandWrapper, "@FocalLength", DbType.Double, DBNull.Value);
		database.AddInParameter(commandWrapper, "@FlashpixVersion", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ColorSpace", DbType.Byte, DBNull.Value);
		database.AddInParameter(commandWrapper, "@SensingMethod", DbType.Byte, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ExposureMode", DbType.Byte, DBNull.Value);
		database.AddInParameter(commandWrapper, "@WhiteBalance", DbType.Byte, DBNull.Value);
		database.AddInParameter(commandWrapper, "@SceneCaptureType", DbType.Byte, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Sharpness", DbType.Byte, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Id", DbType.Guid, DBNull.Value);
	
			// replace all instances of 'AND' and 'OR' because we already set searchUsingOR
			whereClause = whereClause.Replace(" AND ", "|").Replace(" OR ", "|") ; 
			string[] clauses = whereClause.ToLower().Split('|');
		
			// Here's what's going on below: Find a field, then to get the value we
			// drop the field name from the front, trim spaces, drop the '=' sign,
			// trim more spaces, and drop any outer single quotes.
			// Now handles the case when two fields start off the same way - like "Friendly='Yes' AND Friend='john'"
				
			char[] equalSign = {'='};
			char[] singleQuote = {'\''};
	   		foreach (string clause in clauses)
			{
				if (clause.Trim().StartsWith("orientation ") || clause.Trim().StartsWith("orientation="))
				{
					database.SetParameterValue(commandWrapper, "@Orientation", 
						clause.Trim().Remove(0,11).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("ycbcrpositioning ") || clause.Trim().StartsWith("ycbcrpositioning="))
				{
					database.SetParameterValue(commandWrapper, "@YcbCrPositioning", 
						clause.Trim().Remove(0,16).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("exposuretime ") || clause.Trim().StartsWith("exposuretime="))
				{
					database.SetParameterValue(commandWrapper, "@ExposureTime", 
						clause.Trim().Remove(0,12).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("fnumber ") || clause.Trim().StartsWith("fnumber="))
				{
					database.SetParameterValue(commandWrapper, "@Fnumber", 
						clause.Trim().Remove(0,7).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("exposureprogram ") || clause.Trim().StartsWith("exposureprogram="))
				{
					database.SetParameterValue(commandWrapper, "@ExposureProgram", 
						clause.Trim().Remove(0,15).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("isospeedratings ") || clause.Trim().StartsWith("isospeedratings="))
				{
					database.SetParameterValue(commandWrapper, "@IsoSpeedRatings", 
						clause.Trim().Remove(0,15).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("shutterspeedvalue ") || clause.Trim().StartsWith("shutterspeedvalue="))
				{
					database.SetParameterValue(commandWrapper, "@ShutterSpeedValue", 
						clause.Trim().Remove(0,17).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("aperturevalue ") || clause.Trim().StartsWith("aperturevalue="))
				{
					database.SetParameterValue(commandWrapper, "@ApertureValue", 
						clause.Trim().Remove(0,13).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("meteringmode ") || clause.Trim().StartsWith("meteringmode="))
				{
					database.SetParameterValue(commandWrapper, "@MeteringMode", 
						clause.Trim().Remove(0,12).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("flash ") || clause.Trim().StartsWith("flash="))
				{
					database.SetParameterValue(commandWrapper, "@Flash", 
						clause.Trim().Remove(0,5).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("focallength ") || clause.Trim().StartsWith("focallength="))
				{
					database.SetParameterValue(commandWrapper, "@FocalLength", 
						clause.Trim().Remove(0,11).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("flashpixversion ") || clause.Trim().StartsWith("flashpixversion="))
				{
					database.SetParameterValue(commandWrapper, "@FlashpixVersion", 
						clause.Trim().Remove(0,15).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("colorspace ") || clause.Trim().StartsWith("colorspace="))
				{
					database.SetParameterValue(commandWrapper, "@ColorSpace", 
						clause.Trim().Remove(0,10).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("sensingmethod ") || clause.Trim().StartsWith("sensingmethod="))
				{
					database.SetParameterValue(commandWrapper, "@SensingMethod", 
						clause.Trim().Remove(0,13).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("exposuremode ") || clause.Trim().StartsWith("exposuremode="))
				{
					database.SetParameterValue(commandWrapper, "@ExposureMode", 
						clause.Trim().Remove(0,12).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("whitebalance ") || clause.Trim().StartsWith("whitebalance="))
				{
					database.SetParameterValue(commandWrapper, "@WhiteBalance", 
						clause.Trim().Remove(0,12).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("scenecapturetype ") || clause.Trim().StartsWith("scenecapturetype="))
				{
					database.SetParameterValue(commandWrapper, "@SceneCaptureType", 
						clause.Trim().Remove(0,16).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("sharpness ") || clause.Trim().StartsWith("sharpness="))
				{
					database.SetParameterValue(commandWrapper, "@Sharpness", 
						clause.Trim().Remove(0,9).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("id ") || clause.Trim().StartsWith("id="))
				{
					database.SetParameterValue(commandWrapper, "@Id", new Guid(
						clause.Trim().Remove(0,2).Trim().TrimStart(equalSign).Trim().Trim(singleQuote)));
					continue;
				}
	
				throw new ArgumentException("Unable to use this part of the where clause in this version of Find: " + clause);
			}
					
			IDataReader reader = null;
			//Create Collection
			TList<MediaImage> rows = new TList<MediaImage>();
	
				
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "Find", rows)); 

				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
				
				Fill(reader, rows, start, pageLength);
				
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "Find", rows)); 
			}
			finally
			{
				if (reader != null) 
					reader.Close();	
					
				commandWrapper = null;
			}
			return rows;
		}

		#endregion Parsed Find Methods
		
		#region Parameterized Find Methods
		
		/// <summary>
		/// 	Returns rows from the DataSource that meet the parameter conditions.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="parameters">A collection of <see cref="SqlFilterParameter"/> objects.</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <returns>Returns a typed collection of ShutterTale.Entities.MediaImage objects.</returns>
		public override TList<MediaImage> Find(TransactionManager transactionManager, IFilterParameterCollection parameters, string orderBy, int start, int pageLength, out int count)
		{
			SqlFilterParameterCollection filter = null;
			
			if (parameters == null)
				filter = new SqlFilterParameterCollection();
			else 
				filter = parameters.GetParameters();
				
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.Media_Image_Find_Dynamic", typeof(MediaImageColumn), filter, orderBy, start, pageLength);
		
			SqlFilterParameter param;

			for ( int i = 0; i < filter.Count; i++ )
			{
				param = filter[i];
				database.AddInParameter(commandWrapper, param.Name, param.DbType, param.GetValue());
			}

			TList<MediaImage> rows = new TList<MediaImage>();
			IDataReader reader = null;
			
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "Find", rows)); 

				if ( transactionManager != null )
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
				
				Fill(reader, rows, 0, int.MaxValue);
				count = rows.Count;
				
				if ( reader.NextResult() )
				{
					if ( reader.Read() )
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "Find", rows)); 
			}
			finally
			{
				if ( reader != null )
					reader.Close();
					
				commandWrapper = null;
			}
			
			return rows;
		}
		
		#endregion Parameterized Find Methods
		
		#endregion Find Functions
	
		#region GetAll Methods
				
		/// <summary>
		/// 	Gets All rows from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of ShutterTale.Entities.MediaImage objects.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override TList<MediaImage> GetAll(TransactionManager transactionManager, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.Media_Image_Get_List", _useStoredProcedure);
			
			IDataReader reader = null;
		
			//Create Collection
			TList<MediaImage> rows = new TList<MediaImage>();
			
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetAll", rows)); 
					
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				Fill(reader, rows, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetAll", rows)); 
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
					
				commandWrapper = null;	
			}
			return rows;
		}//end getall
		
		#endregion
				
		#region GetPaged Methods
				
		/// <summary>
		/// Gets a page of rows from the DataSource.
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">Number of rows in the DataSource.</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of ShutterTale.Entities.MediaImage objects.</returns>
		public override TList<MediaImage> GetPaged(TransactionManager transactionManager, string whereClause, string orderBy, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.Media_Image_GetPaged", _useStoredProcedure);
		
			
            if (commandWrapper.CommandType == CommandType.Text
                && commandWrapper.CommandText != null)
            {
                commandWrapper.CommandText = commandWrapper.CommandText.Replace(SqlUtil.PAGE_INDEX, string.Concat(SqlUtil.PAGE_INDEX, Guid.NewGuid().ToString("N").Substring(0, 8)));
            }
			
			database.AddInParameter(commandWrapper, "@WhereClause", DbType.String, whereClause);
			database.AddInParameter(commandWrapper, "@OrderBy", DbType.String, orderBy);
			database.AddInParameter(commandWrapper, "@PageIndex", DbType.Int32, start);
			database.AddInParameter(commandWrapper, "@PageSize", DbType.Int32, pageLength);
		
			IDataReader reader = null;
			//Create Collection
			TList<MediaImage> rows = new TList<MediaImage>();
			
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetPaged", rows)); 

				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
				
				Fill(reader, rows, 0, int.MaxValue);
				count = rows.Count;

				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetPaged", rows)); 

			}
			catch(Exception)
			{			
				throw;
			}
			finally
			{
				if (reader != null) 
					reader.Close();
				
				commandWrapper = null;
			}
			
			return rows;
		}
		
		#endregion	
		
		#region Get By Foreign Key Functions
	#endregion
	
		#region Get By Index Functions

		#region GetById
					
		/// <summary>
		/// 	Gets rows from the datasource based on the PK_Media_Image index.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="_id"></param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out parameter to get total records for query.</param>
		/// <returns>Returns an instance of the <see cref="ShutterTale.Entities.MediaImage"/> class.</returns>
		/// <remarks></remarks>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override ShutterTale.Entities.MediaImage GetById(TransactionManager transactionManager, System.Guid _id, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.Media_Image_GetById", _useStoredProcedure);
			
				database.AddInParameter(commandWrapper, "@Id", DbType.Guid, _id);
			
			IDataReader reader = null;
			TList<MediaImage> tmp = new TList<MediaImage>();
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetById", tmp)); 

				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				//Create collection and fill
				Fill(reader, tmp, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetById", tmp));
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
					
				commandWrapper = null;
			}
			
			if (tmp.Count == 1)
			{
				return tmp[0];
			}
			else if (tmp.Count == 0)
			{
				return null;
			}
			else
			{
				throw new DataException("Cannot find the unique instance of the class.");
			}
			
			//return rows;
		}
		
		#endregion

	#endregion Get By Index Functions

		#region Insert Methods
		/// <summary>
		/// Lets you efficiently bulk insert many entities to the database.
		/// </summary>
		/// <param name="transactionManager">The transaction manager.</param>
		/// <param name="entities">The entities.</param>
		/// <remarks>
		///		After inserting into the datasource, the ShutterTale.Entities.MediaImage object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>	
		public override void BulkInsert(TransactionManager transactionManager, TList<ShutterTale.Entities.MediaImage> entities)
		{
			//System.Data.SqlClient.SqlBulkCopy bulkCopy = new System.Data.SqlClient.SqlBulkCopy(this._connectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
			
			System.Data.SqlClient.SqlBulkCopy bulkCopy = null;
	
			if (transactionManager != null && transactionManager.IsOpen)
			{			
				System.Data.SqlClient.SqlConnection cnx = transactionManager.TransactionObject.Connection as System.Data.SqlClient.SqlConnection;
				System.Data.SqlClient.SqlTransaction transaction = transactionManager.TransactionObject as System.Data.SqlClient.SqlTransaction;
				bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, transaction); //, null);
			}
			else
			{
				bulkCopy = new System.Data.SqlClient.SqlBulkCopy(this._connectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
			}
			
			bulkCopy.BulkCopyTimeout = 360;
			bulkCopy.DestinationTableName = "Media_Image";
			
			DataTable dataTable = new DataTable();
			DataColumn col0 = dataTable.Columns.Add("Orientation", typeof(System.Byte));
			col0.AllowDBNull = true;		
			DataColumn col1 = dataTable.Columns.Add("YCbCrPositioning", typeof(System.Byte));
			col1.AllowDBNull = true;		
			DataColumn col2 = dataTable.Columns.Add("ExposureTime", typeof(System.Double));
			col2.AllowDBNull = true;		
			DataColumn col3 = dataTable.Columns.Add("FNumber", typeof(System.Double));
			col3.AllowDBNull = true;		
			DataColumn col4 = dataTable.Columns.Add("ExposureProgram", typeof(System.Byte));
			col4.AllowDBNull = true;		
			DataColumn col5 = dataTable.Columns.Add("ISOSpeedRatings", typeof(System.Int16));
			col5.AllowDBNull = true;		
			DataColumn col6 = dataTable.Columns.Add("ShutterSpeedValue", typeof(System.Double));
			col6.AllowDBNull = true;		
			DataColumn col7 = dataTable.Columns.Add("ApertureValue", typeof(System.Double));
			col7.AllowDBNull = true;		
			DataColumn col8 = dataTable.Columns.Add("MeteringMode", typeof(System.Byte));
			col8.AllowDBNull = true;		
			DataColumn col9 = dataTable.Columns.Add("Flash", typeof(System.Byte));
			col9.AllowDBNull = true;		
			DataColumn col10 = dataTable.Columns.Add("FocalLength", typeof(System.Double));
			col10.AllowDBNull = true;		
			DataColumn col11 = dataTable.Columns.Add("FlashpixVersion", typeof(System.String));
			col11.AllowDBNull = true;		
			DataColumn col12 = dataTable.Columns.Add("ColorSpace", typeof(System.Byte));
			col12.AllowDBNull = true;		
			DataColumn col13 = dataTable.Columns.Add("SensingMethod", typeof(System.Byte));
			col13.AllowDBNull = true;		
			DataColumn col14 = dataTable.Columns.Add("ExposureMode", typeof(System.Byte));
			col14.AllowDBNull = true;		
			DataColumn col15 = dataTable.Columns.Add("WhiteBalance", typeof(System.Byte));
			col15.AllowDBNull = true;		
			DataColumn col16 = dataTable.Columns.Add("SceneCaptureType", typeof(System.Byte));
			col16.AllowDBNull = true;		
			DataColumn col17 = dataTable.Columns.Add("Sharpness", typeof(System.Byte));
			col17.AllowDBNull = true;		
			DataColumn col18 = dataTable.Columns.Add("Id", typeof(System.Guid));
			col18.AllowDBNull = false;		
			
			bulkCopy.ColumnMappings.Add("Orientation", "Orientation");
			bulkCopy.ColumnMappings.Add("YCbCrPositioning", "YCbCrPositioning");
			bulkCopy.ColumnMappings.Add("ExposureTime", "ExposureTime");
			bulkCopy.ColumnMappings.Add("FNumber", "FNumber");
			bulkCopy.ColumnMappings.Add("ExposureProgram", "ExposureProgram");
			bulkCopy.ColumnMappings.Add("ISOSpeedRatings", "ISOSpeedRatings");
			bulkCopy.ColumnMappings.Add("ShutterSpeedValue", "ShutterSpeedValue");
			bulkCopy.ColumnMappings.Add("ApertureValue", "ApertureValue");
			bulkCopy.ColumnMappings.Add("MeteringMode", "MeteringMode");
			bulkCopy.ColumnMappings.Add("Flash", "Flash");
			bulkCopy.ColumnMappings.Add("FocalLength", "FocalLength");
			bulkCopy.ColumnMappings.Add("FlashpixVersion", "FlashpixVersion");
			bulkCopy.ColumnMappings.Add("ColorSpace", "ColorSpace");
			bulkCopy.ColumnMappings.Add("SensingMethod", "SensingMethod");
			bulkCopy.ColumnMappings.Add("ExposureMode", "ExposureMode");
			bulkCopy.ColumnMappings.Add("WhiteBalance", "WhiteBalance");
			bulkCopy.ColumnMappings.Add("SceneCaptureType", "SceneCaptureType");
			bulkCopy.ColumnMappings.Add("Sharpness", "Sharpness");
			bulkCopy.ColumnMappings.Add("Id", "Id");
			
			foreach(ShutterTale.Entities.MediaImage entity in entities)
			{
				if (entity.EntityState != EntityState.Added)
					continue;
					
				DataRow row = dataTable.NewRow();
				
					row["Orientation"] = entity.Orientation.HasValue ? (object) entity.Orientation  : System.DBNull.Value;
							
				
					row["YCbCrPositioning"] = entity.YcbCrPositioning.HasValue ? (object) entity.YcbCrPositioning  : System.DBNull.Value;
							
				
					row["ExposureTime"] = entity.ExposureTime.HasValue ? (object) entity.ExposureTime  : System.DBNull.Value;
							
				
					row["FNumber"] = entity.Fnumber.HasValue ? (object) entity.Fnumber  : System.DBNull.Value;
							
				
					row["ExposureProgram"] = entity.ExposureProgram.HasValue ? (object) entity.ExposureProgram  : System.DBNull.Value;
							
				
					row["ISOSpeedRatings"] = entity.IsoSpeedRatings.HasValue ? (object) entity.IsoSpeedRatings  : System.DBNull.Value;
							
				
					row["ShutterSpeedValue"] = entity.ShutterSpeedValue.HasValue ? (object) entity.ShutterSpeedValue  : System.DBNull.Value;
							
				
					row["ApertureValue"] = entity.ApertureValue.HasValue ? (object) entity.ApertureValue  : System.DBNull.Value;
							
				
					row["MeteringMode"] = entity.MeteringMode.HasValue ? (object) entity.MeteringMode  : System.DBNull.Value;
							
				
					row["Flash"] = entity.Flash.HasValue ? (object) entity.Flash  : System.DBNull.Value;
							
				
					row["FocalLength"] = entity.FocalLength.HasValue ? (object) entity.FocalLength  : System.DBNull.Value;
							
				
					row["FlashpixVersion"] = entity.FlashpixVersion;
							
				
					row["ColorSpace"] = entity.ColorSpace.HasValue ? (object) entity.ColorSpace  : System.DBNull.Value;
							
				
					row["SensingMethod"] = entity.SensingMethod.HasValue ? (object) entity.SensingMethod  : System.DBNull.Value;
							
				
					row["ExposureMode"] = entity.ExposureMode.HasValue ? (object) entity.ExposureMode  : System.DBNull.Value;
							
				
					row["WhiteBalance"] = entity.WhiteBalance.HasValue ? (object) entity.WhiteBalance  : System.DBNull.Value;
							
				
					row["SceneCaptureType"] = entity.SceneCaptureType.HasValue ? (object) entity.SceneCaptureType  : System.DBNull.Value;
							
				
					row["Sharpness"] = entity.Sharpness.HasValue ? (object) entity.Sharpness  : System.DBNull.Value;
							
				
					row["Id"] = entity.Id;
							
				
				dataTable.Rows.Add(row);
			}		
			
			// send the data to the server		
			bulkCopy.WriteToServer(dataTable);		
			
			// update back the state
			foreach(ShutterTale.Entities.MediaImage entity in entities)
			{
				if (entity.EntityState != EntityState.Added)
					continue;
			
				entity.AcceptChanges();
			}
		}
				
		/// <summary>
		/// 	Inserts a ShutterTale.Entities.MediaImage object into the datasource using a transaction.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">ShutterTale.Entities.MediaImage object to insert.</param>
		/// <remarks>
		///		After inserting into the datasource, the ShutterTale.Entities.MediaImage object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>	
		/// <returns>Returns true if operation is successful.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Insert(TransactionManager transactionManager, ShutterTale.Entities.MediaImage entity)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.Media_Image_Insert", _useStoredProcedure);
			
			database.AddInParameter(commandWrapper, "@Orientation", DbType.Byte, (entity.Orientation.HasValue ? (object) entity.Orientation  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@YcbCrPositioning", DbType.Byte, (entity.YcbCrPositioning.HasValue ? (object) entity.YcbCrPositioning  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@ExposureTime", DbType.Double, (entity.ExposureTime.HasValue ? (object) entity.ExposureTime  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@Fnumber", DbType.Double, (entity.Fnumber.HasValue ? (object) entity.Fnumber  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@ExposureProgram", DbType.Byte, (entity.ExposureProgram.HasValue ? (object) entity.ExposureProgram  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@IsoSpeedRatings", DbType.Int16, (entity.IsoSpeedRatings.HasValue ? (object) entity.IsoSpeedRatings  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@ShutterSpeedValue", DbType.Double, (entity.ShutterSpeedValue.HasValue ? (object) entity.ShutterSpeedValue  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@ApertureValue", DbType.Double, (entity.ApertureValue.HasValue ? (object) entity.ApertureValue  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@MeteringMode", DbType.Byte, (entity.MeteringMode.HasValue ? (object) entity.MeteringMode  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@Flash", DbType.Byte, (entity.Flash.HasValue ? (object) entity.Flash  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@FocalLength", DbType.Double, (entity.FocalLength.HasValue ? (object) entity.FocalLength  : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@FlashpixVersion", DbType.String, entity.FlashpixVersion );
			database.AddInParameter(commandWrapper, "@ColorSpace", DbType.Byte, (entity.ColorSpace.HasValue ? (object) entity.ColorSpace  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@SensingMethod", DbType.Byte, (entity.SensingMethod.HasValue ? (object) entity.SensingMethod  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@ExposureMode", DbType.Byte, (entity.ExposureMode.HasValue ? (object) entity.ExposureMode  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@WhiteBalance", DbType.Byte, (entity.WhiteBalance.HasValue ? (object) entity.WhiteBalance  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@SceneCaptureType", DbType.Byte, (entity.SceneCaptureType.HasValue ? (object) entity.SceneCaptureType  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@Sharpness", DbType.Byte, (entity.Sharpness.HasValue ? (object) entity.Sharpness  : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@Id", DbType.Guid, entity.Id );
			
			int results = 0;
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "Insert", entity));
				
			if (transactionManager != null)
			{
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
					
			
			entity.OriginalId = entity.Id;
			
			entity.AcceptChanges();
	
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "Insert", entity));

			return Convert.ToBoolean(results);
		}	
		#endregion

		#region Update Methods
				
		/// <summary>
		/// 	Update an existing row in the datasource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">ShutterTale.Entities.MediaImage object to update.</param>
		/// <remarks>
		///		After updating the datasource, the ShutterTale.Entities.MediaImage object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>
		/// <returns>Returns true if operation is successful.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Update(TransactionManager transactionManager, ShutterTale.Entities.MediaImage entity)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.Media_Image_Update", _useStoredProcedure);
			
			database.AddInParameter(commandWrapper, "@Orientation", DbType.Byte, (entity.Orientation.HasValue ? (object) entity.Orientation : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@YcbCrPositioning", DbType.Byte, (entity.YcbCrPositioning.HasValue ? (object) entity.YcbCrPositioning : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@ExposureTime", DbType.Double, (entity.ExposureTime.HasValue ? (object) entity.ExposureTime : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@Fnumber", DbType.Double, (entity.Fnumber.HasValue ? (object) entity.Fnumber : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@ExposureProgram", DbType.Byte, (entity.ExposureProgram.HasValue ? (object) entity.ExposureProgram : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@IsoSpeedRatings", DbType.Int16, (entity.IsoSpeedRatings.HasValue ? (object) entity.IsoSpeedRatings : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@ShutterSpeedValue", DbType.Double, (entity.ShutterSpeedValue.HasValue ? (object) entity.ShutterSpeedValue : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@ApertureValue", DbType.Double, (entity.ApertureValue.HasValue ? (object) entity.ApertureValue : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@MeteringMode", DbType.Byte, (entity.MeteringMode.HasValue ? (object) entity.MeteringMode : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@Flash", DbType.Byte, (entity.Flash.HasValue ? (object) entity.Flash : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@FocalLength", DbType.Double, (entity.FocalLength.HasValue ? (object) entity.FocalLength : System.DBNull.Value) );
            database.AddInParameter(commandWrapper, "@FlashpixVersion", DbType.String, entity.FlashpixVersion );
			database.AddInParameter(commandWrapper, "@ColorSpace", DbType.Byte, (entity.ColorSpace.HasValue ? (object) entity.ColorSpace : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@SensingMethod", DbType.Byte, (entity.SensingMethod.HasValue ? (object) entity.SensingMethod : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@ExposureMode", DbType.Byte, (entity.ExposureMode.HasValue ? (object) entity.ExposureMode : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@WhiteBalance", DbType.Byte, (entity.WhiteBalance.HasValue ? (object) entity.WhiteBalance : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@SceneCaptureType", DbType.Byte, (entity.SceneCaptureType.HasValue ? (object) entity.SceneCaptureType : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@Sharpness", DbType.Byte, (entity.Sharpness.HasValue ? (object) entity.Sharpness : System.DBNull.Value) );
            database.AddInParameter(commandWrapper, "@Id", DbType.Guid, entity.Id );
			database.AddInParameter(commandWrapper, "@OriginalId", DbType.Guid, entity.OriginalId);
			
			int results = 0;
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "Update", entity));

			if (transactionManager != null)
			{
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
			
			//Stop Tracking Now that it has been updated and persisted.
			if (DataRepository.Provider.EnableEntityTracking)
            {
                EntityManager.StopTracking(entity.EntityTrackingKey);				
            }
			
			entity.OriginalId = entity.Id;
			
			entity.AcceptChanges();
			
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "Update", entity));

			return Convert.ToBoolean(results);
		}
			
		#endregion
		
		#region Custom Methods
	
		#endregion
	}//end class
} // end namespace
