//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audio : Media
    {
        public byte AudioChannels { get; set; }
        public string Duration { get; set; }
        public string AudioCodec { get; set; }
    }
}
