//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public System.Guid Id { get; set; }
        public string Provider { get; set; }
        public string ProviderKey { get; set; }
    
        public virtual Media Medium { get; set; }
    }
}
