//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image : Media
    {
        public Nullable<byte> Orientation { get; set; }
        public Nullable<byte> YCbCrPositioning { get; set; }
        public Nullable<double> ExposureTime { get; set; }
        public Nullable<double> FNumber { get; set; }
        public Nullable<byte> ExposureProgram { get; set; }
        public Nullable<short> ISOSpeedRatings { get; set; }
        public Nullable<double> ShutterSpeedValue { get; set; }
        public Nullable<double> ApertureValue { get; set; }
        public Nullable<byte> MeteringMode { get; set; }
        public Nullable<byte> Flash { get; set; }
        public Nullable<double> FocalLength { get; set; }
        public string FlashpixVersion { get; set; }
        public Nullable<byte> ColorSpace { get; set; }
        public Nullable<byte> SensingMethod { get; set; }
        public Nullable<byte> ExposureMode { get; set; }
        public Nullable<byte> WhiteBalance { get; set; }
        public Nullable<byte> SceneCaptureType { get; set; }
        public Nullable<byte> Sharpness { get; set; }
    }
}
