//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> CaptureDateTime { get; set; }
        public System.DateTime FileDateTime { get; set; }
        public System.DateTime ImportDateTime { get; set; }
        public System.Data.Spatial.DbGeography Location { get; set; }
        public int PixelX { get; set; }
        public int PixelY { get; set; }
        public double Dpi { get; set; }
        public string ContentType { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string SoftwareVersion { get; set; }
        public string Origin { get; set; }
        public int Size { get; set; }
        public string Quadkey18 { get; set; }
    
        public virtual Preview Preview { get; set; }
        public virtual Content Content { get; set; }
    }
}
