//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlProvider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShutterTaleDataModelContainer : DbContext
    {
        public ShutterTaleDataModelContainer()
            : base("name=ShutterTaleDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Media> Media { get; set; }
        public DbSet<Preview> Previews { get; set; }
        public DbSet<Content> Contents { get; set; }
    }
}
