
/*
	File Generated by NetTiers templates [www.nettiers.com]
	Generated on : July 10, 2013
	Important: Do not modify this file. Edit the file MediaTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using ShutterTale.Entities;
using ShutterTale.Data;
using ShutterTale.Data.Bases;

#endregion

namespace ShutterTale.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="Media"/> objects (entity, collection and repository).
    /// </summary>
   public partial class MediaTest
    {
    	// the Media instance used to test the repository.
		protected Media mock;
		
		// the TList<Media> instance used to test the repository.
		protected TList<Media> mockCollection;
		
		protected static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the Media Entity with the {0} --", ShutterTale.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock Media entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.MediaProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.MediaProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all Media objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.MediaProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.MediaProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.MediaProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all Media children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.MediaProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.MediaProvider.DeepLoading += new EntityProviderBaseCore<Media, MediaKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.MediaProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("Media instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.MediaProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock Media entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				Media mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.MediaProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.MediaProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.MediaProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock Media entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (Media)CreateMockInstance(tm);
				DataRepository.MediaProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.MediaProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.MediaProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock Media entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_Media.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock Media entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_Media.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<Media>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a Media collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MediaCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<Media> mockCollection = new TList<Media>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<Media> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a Media collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MediaCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<Media>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<Media> mockCollection = (TList<Media>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<Media> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				Media entity = CreateMockInstance(tm);
				bool result = DataRepository.MediaProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				Media entity = CreateMockInstance(tm);
				bool result = DataRepository.MediaProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				Media t0 = DataRepository.MediaProvider.GetById(tm, entity.Id);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				Media entity = mock.Copy() as Media;
				entity = (Media)mock.Clone();
				Assert.IsTrue(Media.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				Media mock = CreateMockInstance(tm);
				bool result = DataRepository.MediaProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				MediaQuery query = new MediaQuery();
			
				query.AppendEquals(MediaColumn.Id, mock.Id.ToString());
				if(mock.CaptureDateTime != null)
					query.AppendEquals(MediaColumn.CaptureDateTime, mock.CaptureDateTime.ToString());
				query.AppendEquals(MediaColumn.FileDateTime, mock.FileDateTime.ToString());
				query.AppendEquals(MediaColumn.ImportDateTime, mock.ImportDateTime.ToString());
				if(mock.Location != null)
					query.AppendEquals(MediaColumn.Location, mock.Location.ToString());
				query.AppendEquals(MediaColumn.Pixelx, mock.Pixelx.ToString());
				query.AppendEquals(MediaColumn.Pixely, mock.Pixely.ToString());
				query.AppendEquals(MediaColumn.Dpi, mock.Dpi.ToString());
				query.AppendEquals(MediaColumn.ContentType, mock.ContentType.ToString());
				if(mock.Make != null)
					query.AppendEquals(MediaColumn.Make, mock.Make.ToString());
				if(mock.Model != null)
					query.AppendEquals(MediaColumn.Model, mock.Model.ToString());
				if(mock.SoftwareVersion != null)
					query.AppendEquals(MediaColumn.SoftwareVersion, mock.SoftwareVersion.ToString());
				query.AppendEquals(MediaColumn.Origin, mock.Origin.ToString());
				query.AppendEquals(MediaColumn.Size, mock.Size.ToString());
				query.AppendEquals(MediaColumn.Quadkey18, mock.Quadkey18.ToString());
				
				TList<Media> results = DataRepository.MediaProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed Media Entity with mock values.
		///</summary>
		static public Media CreateMockInstance_Generated(TransactionManager tm)
		{		
			Media mock = new Media();
						
			mock.Id = Guid.NewGuid();
			mock.CaptureDateTime = TestUtility.Instance.RandomDateTime();
			mock.FileDateTime = TestUtility.Instance.RandomDateTime();
			mock.ImportDateTime = TestUtility.Instance.RandomDateTime();
			mock.Location = null;
			mock.Pixelx = TestUtility.Instance.RandomNumber();
			mock.Pixely = TestUtility.Instance.RandomNumber();
			mock.Dpi = (double)TestUtility.Instance.RandomNumber();
			mock.ContentType = TestUtility.Instance.RandomString(2, false);;
			mock.Make = TestUtility.Instance.RandomString(2, false);;
			mock.Model = TestUtility.Instance.RandomString(2, false);;
			mock.SoftwareVersion = TestUtility.Instance.RandomString(2, false);;
			mock.Origin = TestUtility.Instance.RandomString(2, false);;
			mock.Size = TestUtility.Instance.RandomNumber();
			mock.Quadkey18 = TestUtility.Instance.RandomString(8, false);;
			
		
			// create a temporary collection and add the item to it
			TList<Media> tempMockCollection = new TList<Media>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (Media)mock;
		}
		
		
		///<summary>
		///  Update the Typed Media Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, Media mock)
		{
			mock.CaptureDateTime = TestUtility.Instance.RandomDateTime();
			mock.FileDateTime = TestUtility.Instance.RandomDateTime();
			mock.ImportDateTime = TestUtility.Instance.RandomDateTime();
			mock.Location = null;
			mock.Pixelx = TestUtility.Instance.RandomNumber();
			mock.Pixely = TestUtility.Instance.RandomNumber();
			mock.Dpi = (double)TestUtility.Instance.RandomNumber();
			mock.ContentType = TestUtility.Instance.RandomString(2, false);;
			mock.Make = TestUtility.Instance.RandomString(2, false);;
			mock.Model = TestUtility.Instance.RandomString(2, false);;
			mock.SoftwareVersion = TestUtility.Instance.RandomString(2, false);;
			mock.Origin = TestUtility.Instance.RandomString(2, false);;
			mock.Size = TestUtility.Instance.RandomNumber();
			mock.Quadkey18 = TestUtility.Instance.RandomString(8, false);;
			
		}
		#endregion
    }
}
