
/*
	File Generated by NetTiers templates [www.nettiers.com]
	Generated on : July 10, 2013
	Important: Do not modify this file. Edit the file MediaVideoTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using ShutterTale.Entities;
using ShutterTale.Data;
using ShutterTale.Data.Bases;

#endregion

namespace ShutterTale.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="MediaVideo"/> objects (entity, collection and repository).
    /// </summary>
   public partial class MediaVideoTest
    {
    	// the MediaVideo instance used to test the repository.
		protected MediaVideo mock;
		
		// the TList<MediaVideo> instance used to test the repository.
		protected TList<MediaVideo> mockCollection;
		
		protected static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the MediaVideo Entity with the {0} --", ShutterTale.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock MediaVideo entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.MediaVideoProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.MediaVideoProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all MediaVideo objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.MediaVideoProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.MediaVideoProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.MediaVideoProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all MediaVideo children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.MediaVideoProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.MediaVideoProvider.DeepLoading += new EntityProviderBaseCore<MediaVideo, MediaVideoKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.MediaVideoProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("MediaVideo instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.MediaVideoProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock MediaVideo entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				MediaVideo mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.MediaVideoProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.MediaVideoProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.MediaVideoProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock MediaVideo entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (MediaVideo)CreateMockInstance(tm);
				DataRepository.MediaVideoProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.MediaVideoProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.MediaVideoProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock MediaVideo entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MediaVideo.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock MediaVideo entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MediaVideo.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<MediaVideo>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a MediaVideo collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MediaVideoCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<MediaVideo> mockCollection = new TList<MediaVideo>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<MediaVideo> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a MediaVideo collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MediaVideoCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<MediaVideo>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<MediaVideo> mockCollection = (TList<MediaVideo>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<MediaVideo> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				MediaVideo entity = CreateMockInstance(tm);
				bool result = DataRepository.MediaVideoProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				MediaVideo entity = CreateMockInstance(tm);
				bool result = DataRepository.MediaVideoProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				MediaVideo t0 = DataRepository.MediaVideoProvider.GetById(tm, entity.Id);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				MediaVideo entity = mock.Copy() as MediaVideo;
				entity = (MediaVideo)mock.Clone();
				Assert.IsTrue(MediaVideo.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				MediaVideo mock = CreateMockInstance(tm);
				bool result = DataRepository.MediaVideoProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				MediaVideoQuery query = new MediaVideoQuery();
			
				if(mock.VideoChannels != null)
					query.AppendEquals(MediaVideoColumn.VideoChannels, mock.VideoChannels.ToString());
				query.AppendEquals(MediaVideoColumn.VideoCodec, mock.VideoCodec.ToString());
				query.AppendEquals(MediaVideoColumn.Id, mock.Id.ToString());
				
				TList<MediaVideo> results = DataRepository.MediaVideoProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed MediaVideo Entity with mock values.
		///</summary>
		static public MediaVideo CreateMockInstance_Generated(TransactionManager tm)
		{		
			MediaVideo mock = new MediaVideo();

            mock.VideoChannels = TestUtility.Instance.RandomByte();
			mock.VideoCodec = TestUtility.Instance.RandomString(2, false);;
			
			//OneToOneRelationship
			MediaAudio mockMediaAudioById = MediaAudioTest.CreateMockInstance(tm);
			DataRepository.MediaAudioProvider.Insert(tm, mockMediaAudioById);
			mock.Id = mockMediaAudioById.Id;
		
			// create a temporary collection and add the item to it
			TList<MediaVideo> tempMockCollection = new TList<MediaVideo>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (MediaVideo)mock;
		}
		
		
		///<summary>
		///  Update the Typed MediaVideo Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, MediaVideo mock)
		{
			mock.VideoChannels = TestUtility.Instance.RandomByte();
			mock.VideoCodec = TestUtility.Instance.RandomString(2, false);;
			
			//OneToOneRelationship
			MediaAudio mockMediaAudioById = MediaAudioTest.CreateMockInstance(tm);
			DataRepository.MediaAudioProvider.Insert(tm, mockMediaAudioById);
			mock.Id = mockMediaAudioById.Id;
					
		}
		#endregion
    }
}
