
/*
	File Generated by NetTiers templates [www.nettiers.com]
	Generated on : July 10, 2013
	Important: Do not modify this file. Edit the file MediaImageTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using ShutterTale.Entities;
using ShutterTale.Data;
using ShutterTale.Data.Bases;

#endregion

namespace ShutterTale.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="MediaImage"/> objects (entity, collection and repository).
    /// </summary>
   public partial class MediaImageTest
    {
    	// the MediaImage instance used to test the repository.
		protected MediaImage mock;
		
		// the TList<MediaImage> instance used to test the repository.
		protected TList<MediaImage> mockCollection;
		
		protected static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the MediaImage Entity with the {0} --", ShutterTale.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock MediaImage entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.MediaImageProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.MediaImageProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all MediaImage objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.MediaImageProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.MediaImageProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.MediaImageProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all MediaImage children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.MediaImageProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.MediaImageProvider.DeepLoading += new EntityProviderBaseCore<MediaImage, MediaImageKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.MediaImageProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("MediaImage instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.MediaImageProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock MediaImage entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				MediaImage mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.MediaImageProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.MediaImageProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.MediaImageProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock MediaImage entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (MediaImage)CreateMockInstance(tm);
				DataRepository.MediaImageProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.MediaImageProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.MediaImageProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock MediaImage entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MediaImage.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock MediaImage entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MediaImage.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<MediaImage>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a MediaImage collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MediaImageCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<MediaImage> mockCollection = new TList<MediaImage>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<MediaImage> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a MediaImage collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MediaImageCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<MediaImage>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<MediaImage> mockCollection = (TList<MediaImage>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<MediaImage> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				MediaImage entity = CreateMockInstance(tm);
				bool result = DataRepository.MediaImageProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				MediaImage entity = CreateMockInstance(tm);
				bool result = DataRepository.MediaImageProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				MediaImage t0 = DataRepository.MediaImageProvider.GetById(tm, entity.Id);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				MediaImage entity = mock.Copy() as MediaImage;
				entity = (MediaImage)mock.Clone();
				Assert.IsTrue(MediaImage.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				MediaImage mock = CreateMockInstance(tm);
				bool result = DataRepository.MediaImageProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				MediaImageQuery query = new MediaImageQuery();
			
				if(mock.Orientation != null)
					query.AppendEquals(MediaImageColumn.Orientation, mock.Orientation.ToString());
				if(mock.YcbCrPositioning != null)
					query.AppendEquals(MediaImageColumn.YcbCrPositioning, mock.YcbCrPositioning.ToString());
				if(mock.ExposureTime != null)
					query.AppendEquals(MediaImageColumn.ExposureTime, mock.ExposureTime.ToString());
				if(mock.Fnumber != null)
					query.AppendEquals(MediaImageColumn.Fnumber, mock.Fnumber.ToString());
				if(mock.ExposureProgram != null)
					query.AppendEquals(MediaImageColumn.ExposureProgram, mock.ExposureProgram.ToString());
				if(mock.IsoSpeedRatings != null)
					query.AppendEquals(MediaImageColumn.IsoSpeedRatings, mock.IsoSpeedRatings.ToString());
				if(mock.ShutterSpeedValue != null)
					query.AppendEquals(MediaImageColumn.ShutterSpeedValue, mock.ShutterSpeedValue.ToString());
				if(mock.ApertureValue != null)
					query.AppendEquals(MediaImageColumn.ApertureValue, mock.ApertureValue.ToString());
				if(mock.MeteringMode != null)
					query.AppendEquals(MediaImageColumn.MeteringMode, mock.MeteringMode.ToString());
				if(mock.Flash != null)
					query.AppendEquals(MediaImageColumn.Flash, mock.Flash.ToString());
				if(mock.FocalLength != null)
					query.AppendEquals(MediaImageColumn.FocalLength, mock.FocalLength.ToString());
				if(mock.FlashpixVersion != null)
					query.AppendEquals(MediaImageColumn.FlashpixVersion, mock.FlashpixVersion.ToString());
				if(mock.ColorSpace != null)
					query.AppendEquals(MediaImageColumn.ColorSpace, mock.ColorSpace.ToString());
				if(mock.SensingMethod != null)
					query.AppendEquals(MediaImageColumn.SensingMethod, mock.SensingMethod.ToString());
				if(mock.ExposureMode != null)
					query.AppendEquals(MediaImageColumn.ExposureMode, mock.ExposureMode.ToString());
				if(mock.WhiteBalance != null)
					query.AppendEquals(MediaImageColumn.WhiteBalance, mock.WhiteBalance.ToString());
				if(mock.SceneCaptureType != null)
					query.AppendEquals(MediaImageColumn.SceneCaptureType, mock.SceneCaptureType.ToString());
				if(mock.Sharpness != null)
					query.AppendEquals(MediaImageColumn.Sharpness, mock.Sharpness.ToString());
				query.AppendEquals(MediaImageColumn.Id, mock.Id.ToString());
				
				TList<MediaImage> results = DataRepository.MediaImageProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed MediaImage Entity with mock values.
		///</summary>
		static public MediaImage CreateMockInstance_Generated(TransactionManager tm)
		{		
			MediaImage mock = new MediaImage();
						
			mock.Orientation = TestUtility.Instance.RandomByte();
			mock.YcbCrPositioning = TestUtility.Instance.RandomByte();
			mock.ExposureTime = (double)TestUtility.Instance.RandomNumber();
			mock.Fnumber = (double)TestUtility.Instance.RandomNumber();
			mock.ExposureProgram = TestUtility.Instance.RandomByte();
			mock.IsoSpeedRatings = TestUtility.Instance.RandomShort();
			mock.ShutterSpeedValue = (double)TestUtility.Instance.RandomNumber();
			mock.ApertureValue = (double)TestUtility.Instance.RandomNumber();
			mock.MeteringMode = TestUtility.Instance.RandomByte();
			mock.Flash = TestUtility.Instance.RandomByte();
			mock.FocalLength = (double)TestUtility.Instance.RandomNumber();
			mock.FlashpixVersion = TestUtility.Instance.RandomString(2, false);;
			mock.ColorSpace = TestUtility.Instance.RandomByte();
			mock.SensingMethod = TestUtility.Instance.RandomByte();
			mock.ExposureMode = TestUtility.Instance.RandomByte();
			mock.WhiteBalance = TestUtility.Instance.RandomByte();
			mock.SceneCaptureType = TestUtility.Instance.RandomByte();
			mock.Sharpness = TestUtility.Instance.RandomByte();
			
			//OneToOneRelationship
			Media mockMediaById = MediaTest.CreateMockInstance(tm);
			DataRepository.MediaProvider.Insert(tm, mockMediaById);
			mock.Id = mockMediaById.Id;
		
			// create a temporary collection and add the item to it
			TList<MediaImage> tempMockCollection = new TList<MediaImage>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (MediaImage)mock;
		}
		
		
		///<summary>
		///  Update the Typed MediaImage Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, MediaImage mock)
		{
			mock.Orientation = TestUtility.Instance.RandomByte();
			mock.YcbCrPositioning = TestUtility.Instance.RandomByte();
			mock.ExposureTime = (double)TestUtility.Instance.RandomNumber();
			mock.Fnumber = (double)TestUtility.Instance.RandomNumber();
			mock.ExposureProgram = TestUtility.Instance.RandomByte();
			mock.IsoSpeedRatings = TestUtility.Instance.RandomShort();
			mock.ShutterSpeedValue = (double)TestUtility.Instance.RandomNumber();
			mock.ApertureValue = (double)TestUtility.Instance.RandomNumber();
			mock.MeteringMode = TestUtility.Instance.RandomByte();
			mock.Flash = TestUtility.Instance.RandomByte();
			mock.FocalLength = (double)TestUtility.Instance.RandomNumber();
			mock.FlashpixVersion = TestUtility.Instance.RandomString(2, false);;
			mock.ColorSpace = TestUtility.Instance.RandomByte();
			mock.SensingMethod = TestUtility.Instance.RandomByte();
			mock.ExposureMode = TestUtility.Instance.RandomByte();
			mock.WhiteBalance = TestUtility.Instance.RandomByte();
			mock.SceneCaptureType = TestUtility.Instance.RandomByte();
			mock.Sharpness = TestUtility.Instance.RandomByte();
			
			//OneToOneRelationship
			Media mockMediaById = MediaTest.CreateMockInstance(tm);
			DataRepository.MediaProvider.Insert(tm, mockMediaById);
			mock.Id = mockMediaById.Id;
					
		}
		#endregion
    }
}
