
/*
	File Generated by NetTiers templates [www.nettiers.com]
	Generated on : July 10, 2013
	Important: Do not modify this file. Edit the file PreviewsTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using ShutterTale.Entities;
using ShutterTale.Data;
using ShutterTale.Data.Bases;

#endregion

namespace ShutterTale.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="Previews"/> objects (entity, collection and repository).
    /// </summary>
   public partial class PreviewsTest
    {
    	// the Previews instance used to test the repository.
		protected Previews mock;
		
		// the TList<Previews> instance used to test the repository.
		protected TList<Previews> mockCollection;
		
		protected static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the Previews Entity with the {0} --", ShutterTale.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock Previews entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.PreviewsProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.PreviewsProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all Previews objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.PreviewsProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.PreviewsProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.PreviewsProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all Previews children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.PreviewsProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.PreviewsProvider.DeepLoading += new EntityProviderBaseCore<Previews, PreviewsKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.PreviewsProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("Previews instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.PreviewsProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock Previews entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				Previews mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.PreviewsProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.PreviewsProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.PreviewsProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock Previews entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (Previews)CreateMockInstance(tm);
				DataRepository.PreviewsProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.PreviewsProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.PreviewsProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock Previews entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_Previews.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock Previews entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_Previews.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<Previews>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a Previews collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_PreviewsCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<Previews> mockCollection = new TList<Previews>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<Previews> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a Previews collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_PreviewsCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<Previews>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<Previews> mockCollection = (TList<Previews>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<Previews> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				Previews entity = CreateMockInstance(tm);
				bool result = DataRepository.PreviewsProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				Previews entity = CreateMockInstance(tm);
				bool result = DataRepository.PreviewsProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				TList<Previews> t0 = DataRepository.PreviewsProvider.GetByMediumId(tm, entity.MediumId);
				Previews t1 = DataRepository.PreviewsProvider.GetById(tm, entity.Id);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				Previews entity = mock.Copy() as Previews;
				entity = (Previews)mock.Clone();
				Assert.IsTrue(Previews.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				Previews mock = CreateMockInstance(tm);
				bool result = DataRepository.PreviewsProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				PreviewsQuery query = new PreviewsQuery();
			
				query.AppendEquals(PreviewsColumn.Id, mock.Id.ToString());
				query.AppendEquals(PreviewsColumn.PreviewType, mock.PreviewType.ToString());
				query.AppendEquals(PreviewsColumn.MediumId, mock.MediumId.ToString());
				
				TList<Previews> results = DataRepository.PreviewsProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed Previews Entity with mock values.
		///</summary>
		static public Previews CreateMockInstance_Generated(TransactionManager tm)
		{		
			Previews mock = new Previews();
						
			mock.Id = Guid.NewGuid();
			mock.Level0 = new byte[] { TestUtility.Instance.RandomByte() };
			mock.Level1 = new byte[] { TestUtility.Instance.RandomByte() };
			mock.Level2 = new byte[] { TestUtility.Instance.RandomByte() };
			mock.Level3 = new byte[] { TestUtility.Instance.RandomByte() };
			mock.PreviewType = TestUtility.Instance.RandomString(2, false);;
			
			//OneToOneRelationship
			Media mockMediaByMediumId = MediaTest.CreateMockInstance(tm);
			DataRepository.MediaProvider.Insert(tm, mockMediaByMediumId);
			mock.MediumId = mockMediaByMediumId.Id;
		
			// create a temporary collection and add the item to it
			TList<Previews> tempMockCollection = new TList<Previews>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (Previews)mock;
		}
		
		
		///<summary>
		///  Update the Typed Previews Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, Previews mock)
		{
			mock.Level0 = new byte[] { TestUtility.Instance.RandomByte() };
			mock.Level1 = new byte[] { TestUtility.Instance.RandomByte() };
			mock.Level2 = new byte[] { TestUtility.Instance.RandomByte() };
			mock.Level3 = new byte[] { TestUtility.Instance.RandomByte() };
			mock.PreviewType = TestUtility.Instance.RandomString(2, false);;
			
			//OneToOneRelationship
			Media mockMediaByMediumId = MediaTest.CreateMockInstance(tm);
			DataRepository.MediaProvider.Insert(tm, mockMediaByMediumId);
			mock.MediumId = mockMediaByMediumId.Id;
					
		}
		#endregion
    }
}
