using System;
using System.ComponentModel;

namespace ShutterTale.Entities
{
	/// <summary>
	///		The data structure representation of the 'Media_Audio' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IMediaAudio 
	{
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Media_Audio"</remarks>
		System.Guid Id { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Guid OriginalId { get; set; }
			
		
		
		/// <summary>
		/// AudioChannels : 
		/// </summary>
		System.Byte  AudioChannels  { get; set; }
		
		/// <summary>
		/// Duration : 
		/// </summary>
		System.String  Duration  { get; set; }
		
		/// <summary>
		/// AudioCodec : 
		/// </summary>
		System.String  AudioCodec  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties
	

		/// <summary>
		///	Holds a  MediaVideo entity object
		///	which is related to this object through the relation _mediaVideoId
		/// </summary>
		MediaVideo MediaVideo { get; set; }

		#endregion Data Properties

	}
}


