using System;
using System.ComponentModel;

namespace ShutterTale.Entities
{
	/// <summary>
	///		The data structure representation of the 'Media' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IMedia 
	{
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Media"</remarks>
		System.Guid Id { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Guid OriginalId { get; set; }
			
		
		
		/// <summary>
		/// CaptureDateTime : 
		/// </summary>
		System.DateTime?  CaptureDateTime  { get; set; }
		
		/// <summary>
		/// FileDateTime : 
		/// </summary>
		System.DateTime  FileDateTime  { get; set; }
		
		/// <summary>
		/// ImportDateTime : 
		/// </summary>
		System.DateTime  ImportDateTime  { get; set; }
		
		/// <summary>
		/// Location : 
		/// </summary>
		System.Object  Location  { get; set; }
		
		/// <summary>
		/// PixelX : 
		/// </summary>
		System.Int32  Pixelx  { get; set; }
		
		/// <summary>
		/// PixelY : 
		/// </summary>
		System.Int32  Pixely  { get; set; }
		
		/// <summary>
		/// Dpi : 
		/// </summary>
		System.Double  Dpi  { get; set; }
		
		/// <summary>
		/// ContentType : 
		/// </summary>
		System.String  ContentType  { get; set; }
		
		/// <summary>
		/// Make : 
		/// </summary>
		System.String  Make  { get; set; }
		
		/// <summary>
		/// Model : 
		/// </summary>
		System.String  Model  { get; set; }
		
		/// <summary>
		/// SoftwareVersion : 
		/// </summary>
		System.String  SoftwareVersion  { get; set; }
		
		/// <summary>
		/// Origin : 
		/// </summary>
		System.String  Origin  { get; set; }
		
		/// <summary>
		/// Size : 
		/// </summary>
		System.Int32  Size  { get; set; }
		
		/// <summary>
		/// Quadkey18 : 
		/// </summary>
		System.String  Quadkey18  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties
	

		/// <summary>
		///	Holds a  MediaImage entity object
		///	which is related to this object through the relation _mediaImageId
		/// </summary>
		MediaImage MediaImage { get; set; }
	

		/// <summary>
		///	Holds a  MediaAudio entity object
		///	which is related to this object through the relation _mediaAudioId
		/// </summary>
		MediaAudio MediaAudio { get; set; }


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _previewsMediumId
		/// </summary>	
		TList<Previews> PreviewsCollection {  get;  set;}	

		#endregion Data Properties

	}
}


