
/*
	File generated by NetTiers templates [www.nettiers.com]
	Generated on : July 10, 2013
	Important: Do not modify this file. Edit the file MediaAudio.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using ShutterTale.Entities.Validation;
#endregion

namespace ShutterTale.Entities
{
	///<summary>
	/// An object representation of the 'Media_Audio' table. [No description found the database]	
	///</summary>
	[DataContract]
	[DataObject, CLSCompliant(true)]
	public abstract partial class MediaAudioBase : EntityBase, IMediaAudio, IEntityId<MediaAudioKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		[DataMember]
		private MediaAudioEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		[DataMember]
		private MediaAudioEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private MediaAudioEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		private TList<MediaAudio> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		public event MediaAudioEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		public event MediaAudioEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="MediaAudioBase"/> instance.
		///</summary>
		public MediaAudioBase()
		{
			this.entityData = new MediaAudioEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="MediaAudioBase"/> instance.
		///</summary>
		///<param name="_audioChannels"></param>
		///<param name="_duration"></param>
		///<param name="_audioCodec"></param>
		///<param name="_id"></param>
		public MediaAudioBase(System.Byte _audioChannels, System.String _duration, System.String _audioCodec, 
			System.Guid _id)
		{
			this.entityData = new MediaAudioEntityData();
			this.backupData = null;

			this.AudioChannels = _audioChannels;
			this.Duration = _duration;
			this.AudioCodec = _audioCodec;
			this.Id = _id;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="MediaAudio"/> instance.
		///</summary>
		///<param name="_audioChannels"></param>
		///<param name="_duration"></param>
		///<param name="_audioCodec"></param>
		///<param name="_id"></param>
		public static MediaAudio CreateMediaAudio(System.Byte _audioChannels, System.String _duration, System.String _audioCodec, 
			System.Guid _id)
		{
			MediaAudio newMediaAudio = new MediaAudio();
			newMediaAudio.AudioChannels = _audioChannels;
			newMediaAudio.Duration = _duration;
			newMediaAudio.AudioCodec = _audioCodec;
			newMediaAudio.Id = _id;
			return newMediaAudio;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the AudioChannels property. 
		///		
		/// </summary>
		/// <value>This type is tinyint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "AudioChannels is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Byte AudioChannels
		{
			get
			{
				return this.entityData.AudioChannels; 
			}
			
			set
			{
				if (this.entityData.AudioChannels == value)
					return;
				
                OnPropertyChanging("AudioChannels");                    
				OnColumnChanging(MediaAudioColumn.AudioChannels, this.entityData.AudioChannels);
				this.entityData.AudioChannels = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MediaAudioColumn.AudioChannels, this.entityData.AudioChannels);
				OnPropertyChanged("AudioChannels");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Duration property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		[Required(ErrorMessage = "Duration is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.String Duration
		{
			get
			{
				return this.entityData.Duration; 
			}
			
			set
			{
				if (this.entityData.Duration == value)
					return;
				
                OnPropertyChanging("Duration");                    
				OnColumnChanging(MediaAudioColumn.Duration, this.entityData.Duration);
				this.entityData.Duration = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MediaAudioColumn.Duration, this.entityData.Duration);
				OnPropertyChanged("Duration");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AudioCodec property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		[Required(ErrorMessage = "AudioCodec is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.String AudioCodec
		{
			get
			{
				return this.entityData.AudioCodec; 
			}
			
			set
			{
				if (this.entityData.AudioCodec == value)
					return;
				
                OnPropertyChanging("AudioCodec");                    
				OnColumnChanging(MediaAudioColumn.AudioCodec, this.entityData.AudioCodec);
				this.entityData.AudioCodec = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MediaAudioColumn.AudioCodec, this.entityData.AudioCodec);
				OnPropertyChanged("AudioCodec");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Id is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public override System.Guid Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(MediaAudioColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MediaAudioColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the Id property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the Id property.</remarks>
		/// <value>This type is uniqueidentifier</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Guid OriginalId
		{
			get { return this.entityData.OriginalId; }
			set { this.entityData.OriginalId = value; }
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Media"/>.
		/// </summary>
		/// <value>The source Media for Id.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Media IdSource
      	{
            get { return entityData.IdSource; }
            set { entityData.IdSource = value; }
      	}
		#endregion
		
		#region Children Collections

		/// <summary>
		///	Holds a MediaVideo object
		///	which is related to this object through the relation MediaVideo
		/// </summary>
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual MediaVideo MediaVideo
		{
			get { return entityData.MediaVideo; }
			set { entityData.MediaVideo = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Duration", "Duration"));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("AudioCodec", "Audio Codec"));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Media_Audio"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"AudioChannels", "Duration", "AudioCodec", "Id"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as MediaAudioEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (MediaAudio) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<MediaAudio>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as MediaAudio);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed MediaAudio Entity 
		///</summary>
		protected virtual MediaAudio Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			MediaAudio copy = new MediaAudio();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.AudioChannels = this.AudioChannels;
				copy.Duration = this.Duration;
				copy.AudioCodec = this.AudioCodec;
				copy.Id = this.Id;
					copy.OriginalId = this.OriginalId;
			
			if (this.IdSource != null && existingCopies.Contains(this.IdSource))
				copy.IdSource = existingCopies[this.IdSource] as Media;
			else
				copy.IdSource = MakeCopyOf(this.IdSource, existingCopies) as Media;
		
			//deep copy nested objects
			copy.MediaVideo = (MediaVideo) MakeCopyOf(this.MediaVideo, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed MediaAudio Entity 
		///</summary>
		public virtual MediaAudio Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed MediaAudio Entity which is a deep copy of the current entity.
		///</summary>
		public virtual MediaAudio DeepCopy()
		{
			return EntityHelper.Clone<MediaAudio>(this as MediaAudio);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as MediaAudioEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new MediaAudioEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as MediaAudioEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(MediaAudioColumn column)
		{
			switch(column)
			{
					case MediaAudioColumn.AudioChannels:
					return entityData.AudioChannels != _originalData.AudioChannels;
					case MediaAudioColumn.Duration:
					return entityData.Duration != _originalData.Duration;
					case MediaAudioColumn.AudioCodec:
					return entityData.AudioCodec != _originalData.AudioCodec;
					case MediaAudioColumn.Id:
					return entityData.Id != _originalData.Id;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< MediaAudioColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.AudioChannels != _originalData.AudioChannels;
			result = result || entityData.Duration != _originalData.Duration;
			result = result || entityData.AudioCodec != _originalData.AudioCodec;
			result = result || entityData.Id != _originalData.Id;
			return result;
		}	
		
		///<summary>
		///  Returns a MediaAudio Entity with the original data.
		///</summary>
		public MediaAudio GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateMediaAudio(
				_originalData.AudioChannels,
				_originalData.Duration,
				_originalData.AudioCodec,
				_originalData.Id
				);
				
			return (MediaAudio)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="MediaAudioBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is MediaAudioBase)
				return ValueEquals(this, (MediaAudioBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="MediaAudioBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.AudioChannels.GetHashCode() ^ 
					this.Duration.GetHashCode() ^ 
					this.AudioCodec.GetHashCode() ^ 
					this.Id.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="MediaAudioBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(MediaAudioBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="MediaAudioBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="MediaAudioBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="MediaAudioBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(MediaAudioBase Object1, MediaAudioBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.AudioChannels != Object2.AudioChannels)
				equal = false;
			if (Object1.Duration != Object2.Duration)
				equal = false;
			if (Object1.AudioCodec != Object2.AudioCodec)
				equal = false;
			if (Object1.Id != Object2.Id)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((MediaAudioBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static MediaAudioComparer GetComparer()
        {
            return new MediaAudioComparer();
        }
        */

        // Comparer delegates back to MediaAudio
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(MediaAudio rhs, MediaAudioColumn which)
        {
            switch (which)
            {
            	
            	
            	case MediaAudioColumn.AudioChannels:
            		return this.AudioChannels.CompareTo(rhs.AudioChannels);
            		
            		                 
            	
            	
            	case MediaAudioColumn.Duration:
            		return this.Duration.CompareTo(rhs.Duration);
            		
            		                 
            	
            	
            	case MediaAudioColumn.AudioCodec:
            		return this.AudioCodec.CompareTo(rhs.AudioCodec);
            		
            		                 
            	
            	
            	case MediaAudioColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<MediaAudioKey> Members
		
		// member variable for the EntityId property
		private MediaAudioKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual MediaAudioKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new MediaAudioKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("MediaAudio")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{5}{4}- AudioChannels: {0}{4}- Duration: {1}{4}- AudioCodec: {2}{4}- Id: {3}{4}{6}", 
				this.AudioChannels,
				this.Duration,
				this.AudioCodec,
				this.Id,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Media_Audio' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[DataContract]
	internal protected class MediaAudioEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Media_Audio"</remarks>
		[DataMember]
		public System.Guid Id;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		[DataMember]
		public System.Guid OriginalId;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// AudioChannels : 
		/// </summary>
		[DataMember]
		public System.Byte AudioChannels = (byte)0;
		
		/// <summary>
		/// Duration : 
		/// </summary>
		[DataMember]
		public System.String Duration = string.Empty;
		
		/// <summary>
		/// AudioCodec : 
		/// </summary>
		[DataMember]
		public System.String AudioCodec = string.Empty;
		#endregion
			
		#region Source Foreign Key Property
				
		private Media _idSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Media"/>.
		/// </summary>
		/// <value>The source Media for Id.</value>
		[DataMember]
		[Browsable(false)]
		public virtual Media IdSource
      	{
            get { return this._idSource; }
            set { this._idSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#region MediaVideo
		
		private MediaVideo _mediaVideoId;
		
		/// <summary>
		///	Holds a  MediaVideo entity object
		///	which is related to this object through the relation _mediaVideoId
		/// </summary>
		[DataMember]
		public MediaVideo MediaVideo
		{
			get {		return _mediaVideoId;		}
			set { 	_mediaVideoId = value; 	}
		}
		
		#endregion 

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			MediaAudioEntityData _tmp = new MediaAudioEntityData();
						
			_tmp.Id = this.Id;
			_tmp.OriginalId = this.OriginalId;
			
			_tmp.AudioChannels = this.AudioChannels;
			_tmp.Duration = this.Duration;
			_tmp.AudioCodec = this.AudioCodec;
			
			#region Source Parent Composite Entities
			if (this.IdSource != null)
				_tmp.IdSource = MakeCopyOf(this.IdSource) as Media;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._mediaVideoId != null)
				_tmp.MediaVideo = (MediaVideo) MakeCopyOf(this.MediaVideo); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			MediaAudioEntityData _tmp = new MediaAudioEntityData();
						
			_tmp.Id = this.Id;
			_tmp.OriginalId = this.OriginalId;
			
			_tmp.AudioChannels = this.AudioChannels;
			_tmp.Duration = this.Duration;
			_tmp.AudioCodec = this.AudioCodec;
			
			#region Source Parent Composite Entities
			if (this.IdSource != null && existingCopies.Contains(this.IdSource))
				_tmp.IdSource = existingCopies[this.IdSource] as Media;
			else
				_tmp.IdSource = MakeCopyOf(this.IdSource, existingCopies) as Media;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.MediaVideo = (MediaVideo) MakeCopyOf(this.MediaVideo, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region DataContract serialization
		
		bool _deserializing = false;
		
		/// <summary>
		/// Called before deserializing the type.
		/// </summary>
		[OnDeserializingAttribute]
		private void Initialize_BeforeDeserializing(StreamingContext context)
		{
			this._deserializing = true;
		
			this.entityData = new MediaAudioEntityData();
			this.backupData = null;
			
			AddValidationRules();
		}
		
		/// <summary>
		/// Called after deserializing the type.
		/// </summary>
		[OnDeserializedAttribute ]
		private void Initialize_Deserialized(StreamingContext context)
		{
			this._deserializing = false;
		}
				
		#endregion
		
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MediaAudioColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(MediaAudioColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MediaAudioColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(MediaAudioColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MediaAudioColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(MediaAudioColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				MediaAudioEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new MediaAudioEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MediaAudioColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(MediaAudioColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				MediaAudioEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new MediaAudioEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region MediaAudioEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="MediaAudio"/> object.
	/// </remarks>
	public class MediaAudioEventArgs : System.EventArgs
	{
		private MediaAudioColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the MediaAudioEventArgs class.
		///</summary>
		public MediaAudioEventArgs(MediaAudioColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the MediaAudioEventArgs class.
		///</summary>
		public MediaAudioEventArgs(MediaAudioColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The MediaAudioColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="MediaAudioColumn" />
		public MediaAudioColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all MediaAudio related events.
	///</summary>
	public delegate void MediaAudioEventHandler(object sender, MediaAudioEventArgs e);
	
	#region MediaAudioComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class MediaAudioComparer : System.Collections.Generic.IComparer<MediaAudio>
	{
		MediaAudioColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:MediaAudioComparer"/> class.
        /// </summary>
		public MediaAudioComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:MediaAudioComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public MediaAudioComparer(MediaAudioColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="MediaAudio"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="MediaAudio"/> to compare.</param>
        /// <param name="b">The second <c>MediaAudio</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(MediaAudio a, MediaAudio b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(MediaAudio entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(MediaAudio a, MediaAudio b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public MediaAudioColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region MediaAudioKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="MediaAudio"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class MediaAudioKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the MediaAudioKey class.
		/// </summary>
		public MediaAudioKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the MediaAudioKey class.
		/// </summary>
		public MediaAudioKey(MediaAudioBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the MediaAudioKey class.
		/// </summary>
		public MediaAudioKey(System.Guid _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private MediaAudioBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public MediaAudioBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Guid _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Guid Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Guid) EntityUtil.ChangeType(values["Id"], typeof(System.Guid)) : Guid.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region MediaAudioColumn Enum
	
	/// <summary>
	/// Enumerate the MediaAudio columns.
	/// </summary>
	[Serializable]
	public enum MediaAudioColumn : int
	{
		/// <summary>
		/// AudioChannels : 
		/// </summary>
		[EnumTextValue("Audio Channels")]
		[ColumnEnum("AudioChannels", typeof(System.Byte), System.Data.DbType.Byte, false, false, false)]
		AudioChannels = 1,
		/// <summary>
		/// Duration : 
		/// </summary>
		[EnumTextValue("Duration")]
		[ColumnEnum("Duration", typeof(System.String), System.Data.DbType.String, false, false, false)]
		Duration = 2,
		/// <summary>
		/// AudioCodec : 
		/// </summary>
		[EnumTextValue("Audio Codec")]
		[ColumnEnum("AudioCodec", typeof(System.String), System.Data.DbType.String, false, false, false)]
		AudioCodec = 3,
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("Id", typeof(System.Guid), System.Data.DbType.Guid, true, false, false)]
		Id = 4
	}//End enum

	#endregion MediaAudioColumn Enum

} // end namespace
