
/*
	File generated by NetTiers templates [www.nettiers.com]
	Generated on : July 10, 2013
	Important: Do not modify this file. Edit the file Previews.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using ShutterTale.Entities.Validation;
#endregion

namespace ShutterTale.Entities
{
	///<summary>
	/// An object representation of the 'Previews' table. [No description found the database]	
	///</summary>
	[DataContract]
	[DataObject, CLSCompliant(true)]
	public abstract partial class PreviewsBase : EntityBase, IPreviews, IEntityId<PreviewsKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		[DataMember]
		private PreviewsEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		[DataMember]
		private PreviewsEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private PreviewsEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		private TList<Previews> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		public event PreviewsEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		public event PreviewsEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="PreviewsBase"/> instance.
		///</summary>
		public PreviewsBase()
		{
			this.entityData = new PreviewsEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="PreviewsBase"/> instance.
		///</summary>
		///<param name="_id"></param>
		///<param name="_level0"></param>
		///<param name="_level1"></param>
		///<param name="_level2"></param>
		///<param name="_level3"></param>
		///<param name="_previewType"></param>
		///<param name="_mediumId"></param>
		public PreviewsBase(System.Guid _id, System.Byte[] _level0, System.Byte[] _level1, 
			System.Byte[] _level2, System.Byte[] _level3, System.String _previewType, System.Guid _mediumId)
		{
			this.entityData = new PreviewsEntityData();
			this.backupData = null;

			this.Id = _id;
			this.Level0 = _level0;
			this.Level1 = _level1;
			this.Level2 = _level2;
			this.Level3 = _level3;
			this.PreviewType = _previewType;
			this.MediumId = _mediumId;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Previews"/> instance.
		///</summary>
		///<param name="_id"></param>
		///<param name="_level0"></param>
		///<param name="_level1"></param>
		///<param name="_level2"></param>
		///<param name="_level3"></param>
		///<param name="_previewType"></param>
		///<param name="_mediumId"></param>
		public static Previews CreatePreviews(System.Guid _id, System.Byte[] _level0, System.Byte[] _level1, 
			System.Byte[] _level2, System.Byte[] _level3, System.String _previewType, System.Guid _mediumId)
		{
			Previews newPreviews = new Previews();
			newPreviews.Id = _id;
			newPreviews.Level0 = _level0;
			newPreviews.Level1 = _level1;
			newPreviews.Level2 = _level2;
			newPreviews.Level3 = _level3;
			newPreviews.PreviewType = _previewType;
			newPreviews.MediumId = _mediumId;
			return newPreviews;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Id is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public override System.Guid Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(PreviewsColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PreviewsColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the Id property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the Id property.</remarks>
		/// <value>This type is uniqueidentifier</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Guid OriginalId
		{
			get { return this.entityData.OriginalId; }
			set { this.entityData.OriginalId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the Level0 property. 
		///		
		/// </summary>
		/// <value>This type is varbinary.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Byte[] Level0
		{
			get
			{
				return this.entityData.Level0; 
			}
			
			set
			{
				if (this.entityData.Level0 == value)
					return;
				
                OnPropertyChanging("Level0");                    
				OnColumnChanging(PreviewsColumn.Level0, this.entityData.Level0);
				this.entityData.Level0 = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PreviewsColumn.Level0, this.entityData.Level0);
				OnPropertyChanged("Level0");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Level1 property. 
		///		
		/// </summary>
		/// <value>This type is varbinary.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Byte[] Level1
		{
			get
			{
				return this.entityData.Level1; 
			}
			
			set
			{
				if (this.entityData.Level1 == value)
					return;
				
                OnPropertyChanging("Level1");                    
				OnColumnChanging(PreviewsColumn.Level1, this.entityData.Level1);
				this.entityData.Level1 = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PreviewsColumn.Level1, this.entityData.Level1);
				OnPropertyChanged("Level1");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Level2 property. 
		///		
		/// </summary>
		/// <value>This type is varbinary.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Byte[] Level2
		{
			get
			{
				return this.entityData.Level2; 
			}
			
			set
			{
				if (this.entityData.Level2 == value)
					return;
				
                OnPropertyChanging("Level2");                    
				OnColumnChanging(PreviewsColumn.Level2, this.entityData.Level2);
				this.entityData.Level2 = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PreviewsColumn.Level2, this.entityData.Level2);
				OnPropertyChanged("Level2");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Level3 property. 
		///		
		/// </summary>
		/// <value>This type is varbinary.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Byte[] Level3
		{
			get
			{
				return this.entityData.Level3; 
			}
			
			set
			{
				if (this.entityData.Level3 == value)
					return;
				
                OnPropertyChanging("Level3");                    
				OnColumnChanging(PreviewsColumn.Level3, this.entityData.Level3);
				this.entityData.Level3 = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PreviewsColumn.Level3, this.entityData.Level3);
				OnPropertyChanged("Level3");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PreviewType property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		[Required(ErrorMessage = "PreviewType is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.String PreviewType
		{
			get
			{
				return this.entityData.PreviewType; 
			}
			
			set
			{
				if (this.entityData.PreviewType == value)
					return;
				
                OnPropertyChanging("PreviewType");                    
				OnColumnChanging(PreviewsColumn.PreviewType, this.entityData.PreviewType);
				this.entityData.PreviewType = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PreviewsColumn.PreviewType, this.entityData.PreviewType);
				OnPropertyChanged("PreviewType");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MediumId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "MediumId is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Guid MediumId
		{
			get
			{
				return this.entityData.MediumId; 
			}
			
			set
			{
				if (this.entityData.MediumId == value)
					return;
				
                OnPropertyChanging("MediumId");                    
				OnColumnChanging(PreviewsColumn.MediumId, this.entityData.MediumId);
				this.entityData.MediumId = value;
				if ( !this._deserializing && this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PreviewsColumn.MediumId, this.entityData.MediumId);
				OnPropertyChanged("MediumId");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Media"/>.
		/// </summary>
		/// <value>The source Media for MediumId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Media MediumIdSource
      	{
            get { return entityData.MediumIdSource; }
            set { entityData.MediumIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("PreviewType", "Preview Type"));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Previews"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Id", "Level0", "Level1", "Level2", "Level3", "PreviewType", "Medium_Id"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as PreviewsEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Previews) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Previews>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Previews);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Previews Entity 
		///</summary>
		protected virtual Previews Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Previews copy = new Previews();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
					copy.OriginalId = this.OriginalId;
				copy.Level0 = this.Level0;
				copy.Level1 = this.Level1;
				copy.Level2 = this.Level2;
				copy.Level3 = this.Level3;
				copy.PreviewType = this.PreviewType;
				copy.MediumId = this.MediumId;
			
			if (this.MediumIdSource != null && existingCopies.Contains(this.MediumIdSource))
				copy.MediumIdSource = existingCopies[this.MediumIdSource] as Media;
			else
				copy.MediumIdSource = MakeCopyOf(this.MediumIdSource, existingCopies) as Media;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Previews Entity 
		///</summary>
		public virtual Previews Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Previews Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Previews DeepCopy()
		{
			return EntityHelper.Clone<Previews>(this as Previews);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as PreviewsEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new PreviewsEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as PreviewsEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(PreviewsColumn column)
		{
			switch(column)
			{
					case PreviewsColumn.Id:
					return entityData.Id != _originalData.Id;
					case PreviewsColumn.Level0:
					return entityData.Level0 != _originalData.Level0;
					case PreviewsColumn.Level1:
					return entityData.Level1 != _originalData.Level1;
					case PreviewsColumn.Level2:
					return entityData.Level2 != _originalData.Level2;
					case PreviewsColumn.Level3:
					return entityData.Level3 != _originalData.Level3;
					case PreviewsColumn.PreviewType:
					return entityData.PreviewType != _originalData.PreviewType;
					case PreviewsColumn.MediumId:
					return entityData.MediumId != _originalData.MediumId;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< PreviewsColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.Level0 != _originalData.Level0;
			result = result || entityData.Level1 != _originalData.Level1;
			result = result || entityData.Level2 != _originalData.Level2;
			result = result || entityData.Level3 != _originalData.Level3;
			result = result || entityData.PreviewType != _originalData.PreviewType;
			result = result || entityData.MediumId != _originalData.MediumId;
			return result;
		}	
		
		///<summary>
		///  Returns a Previews Entity with the original data.
		///</summary>
		public Previews GetOriginalEntity()
		{
			if (_originalData != null)
				return CreatePreviews(
				_originalData.Id,
				_originalData.Level0,
				_originalData.Level1,
				_originalData.Level2,
				_originalData.Level3,
				_originalData.PreviewType,
				_originalData.MediumId
				);
				
			return (Previews)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="PreviewsBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is PreviewsBase)
				return ValueEquals(this, (PreviewsBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="PreviewsBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					((this.Level0 == null) ? string.Empty : this.Level0.ToString()).GetHashCode() ^ 
					((this.Level1 == null) ? string.Empty : this.Level1.ToString()).GetHashCode() ^ 
					((this.Level2 == null) ? string.Empty : this.Level2.ToString()).GetHashCode() ^ 
					((this.Level3 == null) ? string.Empty : this.Level3.ToString()).GetHashCode() ^ 
					this.PreviewType.GetHashCode() ^ 
					this.MediumId.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="PreviewsBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(PreviewsBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="PreviewsBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="PreviewsBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="PreviewsBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(PreviewsBase Object1, PreviewsBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if ( Object1.Level0 != null && Object2.Level0 != null )
			{
				if (Object1.Level0 != Object2.Level0)
					equal = false;
			}
			else if (Object1.Level0 == null ^ Object2.Level0 == null )
			{
				equal = false;
			}
			if ( Object1.Level1 != null && Object2.Level1 != null )
			{
				if (Object1.Level1 != Object2.Level1)
					equal = false;
			}
			else if (Object1.Level1 == null ^ Object2.Level1 == null )
			{
				equal = false;
			}
			if ( Object1.Level2 != null && Object2.Level2 != null )
			{
				if (Object1.Level2 != Object2.Level2)
					equal = false;
			}
			else if (Object1.Level2 == null ^ Object2.Level2 == null )
			{
				equal = false;
			}
			if ( Object1.Level3 != null && Object2.Level3 != null )
			{
				if (Object1.Level3 != Object2.Level3)
					equal = false;
			}
			else if (Object1.Level3 == null ^ Object2.Level3 == null )
			{
				equal = false;
			}
			if (Object1.PreviewType != Object2.PreviewType)
				equal = false;
			if (Object1.MediumId != Object2.MediumId)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((PreviewsBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static PreviewsComparer GetComparer()
        {
            return new PreviewsComparer();
        }
        */

        // Comparer delegates back to Previews
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Previews rhs, PreviewsColumn which)
        {
            switch (which)
            {
            	
            	
            	case PreviewsColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            		                 
            	
            		                 
            	
            		                 
            	
            		                 
            	
            	
            	case PreviewsColumn.PreviewType:
            		return this.PreviewType.CompareTo(rhs.PreviewType);
            		
            		                 
            	
            	
            	case PreviewsColumn.MediumId:
            		return this.MediumId.CompareTo(rhs.MediumId);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<PreviewsKey> Members
		
		// member variable for the EntityId property
		private PreviewsKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual PreviewsKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new PreviewsKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Previews")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{8}{7}- Id: {0}{7}- Level0: {1}{7}- Level1: {2}{7}- Level2: {3}{7}- Level3: {4}{7}- PreviewType: {5}{7}- MediumId: {6}{7}{9}", 
				this.Id,
				(this.Level0 == null) ? string.Empty : this.Level0.ToString(),
				(this.Level1 == null) ? string.Empty : this.Level1.ToString(),
				(this.Level2 == null) ? string.Empty : this.Level2.ToString(),
				(this.Level3 == null) ? string.Empty : this.Level3.ToString(),
				this.PreviewType,
				this.MediumId,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Previews' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[DataContract]
	internal protected class PreviewsEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Previews"</remarks>
		[DataMember]
		public System.Guid Id;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		[DataMember]
		public System.Guid OriginalId;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// Level0 : 
		/// </summary>
		[DataMember]
		public System.Byte[] Level0 = null;
		
		/// <summary>
		/// Level1 : 
		/// </summary>
		[DataMember]
		public System.Byte[] Level1 = null;
		
		/// <summary>
		/// Level2 : 
		/// </summary>
		[DataMember]
		public System.Byte[] Level2 = null;
		
		/// <summary>
		/// Level3 : 
		/// </summary>
		[DataMember]
		public System.Byte[] Level3 = null;
		
		/// <summary>
		/// PreviewType : 
		/// </summary>
		[DataMember]
		public System.String PreviewType = string.Empty;
		
		/// <summary>
		/// Medium_Id : 
		/// </summary>
		[DataMember]
		public System.Guid MediumId = Guid.Empty;
		#endregion
			
		#region Source Foreign Key Property
				
		private Media _mediumIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Media"/>.
		/// </summary>
		/// <value>The source Media for MediumId.</value>
		[DataMember]
		[Browsable(false)]
		public virtual Media MediumIdSource
      	{
            get { return this._mediumIdSource; }
            set { this._mediumIdSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			PreviewsEntityData _tmp = new PreviewsEntityData();
						
			_tmp.Id = this.Id;
			_tmp.OriginalId = this.OriginalId;
			
			_tmp.Level0 = this.Level0;
			_tmp.Level1 = this.Level1;
			_tmp.Level2 = this.Level2;
			_tmp.Level3 = this.Level3;
			_tmp.PreviewType = this.PreviewType;
			_tmp.MediumId = this.MediumId;
			
			#region Source Parent Composite Entities
			if (this.MediumIdSource != null)
				_tmp.MediumIdSource = MakeCopyOf(this.MediumIdSource) as Media;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			PreviewsEntityData _tmp = new PreviewsEntityData();
						
			_tmp.Id = this.Id;
			_tmp.OriginalId = this.OriginalId;
			
			_tmp.Level0 = this.Level0;
			_tmp.Level1 = this.Level1;
			_tmp.Level2 = this.Level2;
			_tmp.Level3 = this.Level3;
			_tmp.PreviewType = this.PreviewType;
			_tmp.MediumId = this.MediumId;
			
			#region Source Parent Composite Entities
			if (this.MediumIdSource != null && existingCopies.Contains(this.MediumIdSource))
				_tmp.MediumIdSource = existingCopies[this.MediumIdSource] as Media;
			else
				_tmp.MediumIdSource = MakeCopyOf(this.MediumIdSource, existingCopies) as Media;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region DataContract serialization
		
		bool _deserializing = false;
		
		/// <summary>
		/// Called before deserializing the type.
		/// </summary>
		[OnDeserializingAttribute]
		private void Initialize_BeforeDeserializing(StreamingContext context)
		{
			this._deserializing = true;
		
			this.entityData = new PreviewsEntityData();
			this.backupData = null;
			
			AddValidationRules();
		}
		
		/// <summary>
		/// Called after deserializing the type.
		/// </summary>
		[OnDeserializedAttribute ]
		private void Initialize_Deserialized(StreamingContext context)
		{
			this._deserializing = false;
		}
				
		#endregion
		
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PreviewsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(PreviewsColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PreviewsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(PreviewsColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PreviewsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(PreviewsColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				PreviewsEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new PreviewsEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PreviewsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(PreviewsColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				PreviewsEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new PreviewsEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region PreviewsEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Previews"/> object.
	/// </remarks>
	public class PreviewsEventArgs : System.EventArgs
	{
		private PreviewsColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the PreviewsEventArgs class.
		///</summary>
		public PreviewsEventArgs(PreviewsColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the PreviewsEventArgs class.
		///</summary>
		public PreviewsEventArgs(PreviewsColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The PreviewsColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="PreviewsColumn" />
		public PreviewsColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Previews related events.
	///</summary>
	public delegate void PreviewsEventHandler(object sender, PreviewsEventArgs e);
	
	#region PreviewsComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class PreviewsComparer : System.Collections.Generic.IComparer<Previews>
	{
		PreviewsColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:PreviewsComparer"/> class.
        /// </summary>
		public PreviewsComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PreviewsComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public PreviewsComparer(PreviewsColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="Previews"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="Previews"/> to compare.</param>
        /// <param name="b">The second <c>Previews</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Previews a, Previews b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Previews entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Previews a, Previews b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public PreviewsColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region PreviewsKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Previews"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class PreviewsKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the PreviewsKey class.
		/// </summary>
		public PreviewsKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the PreviewsKey class.
		/// </summary>
		public PreviewsKey(PreviewsBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the PreviewsKey class.
		/// </summary>
		public PreviewsKey(System.Guid _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private PreviewsBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public PreviewsBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Guid _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Guid Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Guid) EntityUtil.ChangeType(values["Id"], typeof(System.Guid)) : Guid.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region PreviewsColumn Enum
	
	/// <summary>
	/// Enumerate the Previews columns.
	/// </summary>
	[Serializable]
	public enum PreviewsColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("Id", typeof(System.Guid), System.Data.DbType.Guid, true, false, false)]
		Id = 1,
		/// <summary>
		/// Level0 : 
		/// </summary>
		[EnumTextValue("Level0")]
		[ColumnEnum("Level0", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, true)]
		Level0 = 2,
		/// <summary>
		/// Level1 : 
		/// </summary>
		[EnumTextValue("Level1")]
		[ColumnEnum("Level1", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, true)]
		Level1 = 3,
		/// <summary>
		/// Level2 : 
		/// </summary>
		[EnumTextValue("Level2")]
		[ColumnEnum("Level2", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, true)]
		Level2 = 4,
		/// <summary>
		/// Level3 : 
		/// </summary>
		[EnumTextValue("Level3")]
		[ColumnEnum("Level3", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, true)]
		Level3 = 5,
		/// <summary>
		/// PreviewType : 
		/// </summary>
		[EnumTextValue("Preview Type")]
		[ColumnEnum("PreviewType", typeof(System.String), System.Data.DbType.String, false, false, false)]
		PreviewType = 6,
		/// <summary>
		/// MediumId : 
		/// </summary>
		[EnumTextValue("Medium Id")]
		[ColumnEnum("Medium_Id", typeof(System.Guid), System.Data.DbType.Guid, false, false, false)]
		MediumId = 7
	}//End enum

	#endregion PreviewsColumn Enum

} // end namespace
